name: core_network_model
description: This package provides network operations.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.5.1

dependencies:
  freezed_annotation: 2.4.4
  json_annotation: 4.9.0

dev_dependencies:
  build_runner: 2.4.12
  freezed: 2.5.7
  json_serializable: 6.8.0
  yumemi_lints: 2.2.0
