name: core_common
description: This package provides convenience functions and other functions commonly used in packages.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.4.4

dependencies:
  anyhow: 1.3.1
  collection: 1.18.0
  rust_core: 1.2.2
  simple_logger: 1.9.0+3

dev_dependencies:
  test: 1.25.8
  yumemi_lints: 2.1.0
