name: feature_home
description: "This package provides home features."
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.5.3
  flutter: 3.24.3

dependencies:
  core_common:
    path: ../../core/common
  core_designsystem:
    path: ../../core/designsystem
  core_domain:
    path: ../../core/domain
  core_model:
    path: ../../core/model
  core_ui:
    path: ../../core/ui
  flutter:
    sdk: flutter
  flutter_hooks: 0.20.5
  flutter_localizations:
    sdk: flutter
  go_router: 14.2.7
  hooks_riverpod: 2.5.2
  intl: 0.19.0

dev_dependencies:
  core_testing:
    path: ../../core/testing
  flutter_test:
    sdk: flutter
  yumemi_lints: 2.2.0

flutter:
