name: core_analytics_firebase
description: This package provides functions for analysis.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.5.3
  flutter: 3.24.3

dependencies:
  core_analytics:
    path: ../analytics
  core_common:
    path: ../common
  firebase_analytics: 11.3.1
  riverpod_annotation: 2.3.5

dependency_overrides:
  # workaround
  meta: 1.15.0
  # workaround
  test_api: 0.7.2

dev_dependencies:
  build_runner: 2.4.12
  riverpod_generator: 2.4.3
  test: 1.25.8
  yumemi_lints: 2.2.0
