name: core_model
description: This package provides model classes.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.5.3

dependencies:
  core_common:
    path: ../common
  freezed_annotation: 2.4.4
  riverpod: 2.6.1
  riverpod_annotation: 2.6.1

dev_dependencies:
  build_runner: 2.4.13
  freezed: 2.5.7
  riverpod_generator: 2.6.1
  test: 1.25.8
  yumemi_lints: 2.2.0
