name: core_database
description: This package provides local database operations.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.4.0

dependencies:
  core_common:
    path: ../common
  core_model:
    path: ../model
  isar:
    hosted: https://pub.isar-community.dev/
    version: 4.0.3
  riverpod_annotation: 2.3.5

dev_dependencies:
  build_runner: 2.4.10
  core_testing:
    path: ../testing
  riverpod_generator: 2.4.2
  test: 1.25.5
  yumemi_lints: 1.7.0
