name: core_database_isar
description: This package provides local database operations using Isar.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.5.2

dependencies:
  core_common:
    path: ../common
  core_database:
    path: ../database
  core_model:
    path: ../model
  isar:
    hosted: https://pub.isar-community.dev/
    version: 4.0.3
  riverpod_annotation: 2.3.5

dev_dependencies:
  build_runner: 2.4.12
  core_testing:
    path: ../testing
  riverpod_generator: 2.4.3
  test: 1.25.8
  yumemi_lints: 2.2.0
