name: core_designsystem
description: This package provides style definitions, themes, etc.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.5.2
  flutter: 3.24.2

dependencies:
  core_common:
    path: ../common
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: 0.2.6
  flutter_localizations:
    sdk: flutter
  flutter_svg: 2.0.10+1
  gap: 3.0.1
  intl: 0.19.0

dev_dependencies:
  build_runner: 2.4.12
  core_testing:
    path: ../testing
  flutter_gen_runner: 5.7.0
  flutter_test:
    sdk: flutter
  yumemi_lints: 2.2.0

flutter:
  assets:
    - assets/images/

flutter_gen:
  output: lib/src/gen/assets
  assets:
    outputs:
      package_parameter_enabled: true
