name: core_ui
description: This package provides a UI that depends on the model class and is used by all packages.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.5.0
  flutter: 3.24.0

dependencies:
  core_common:
    path: ../common
  core_designsystem:
    path: ../designsystem
  core_model:
    path: ../model
  flutter:
    sdk: flutter
  flutter_hooks: 0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: 2.5.1
  freezed_annotation: 2.4.4
  intl: 0.19.0
  riverpod_annotation: 2.3.5

dev_dependencies:
  build_runner: 2.4.11
  core_testing:
    path: ../testing
  flutter_test:
    sdk: flutter
  freezed: 2.5.7
  riverpod_generator: 2.4.2
  yumemi_lints: 2.1.0

dependency_overrides:
  # workaround
  meta: 1.15.0

flutter:
