name: core_datastore
description: This package provides local preferences operations.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.5.1

dependencies:
  core_common:
    path: ../common
  core_model:
    path: ../model
  riverpod_annotation: 2.3.5

dev_dependencies:
  build_runner: 2.4.12
  riverpod_generator: 2.4.2
  yumemi_lints: 2.1.0
